dist:     trusty    
sudo:     required  

language: c         
                    
os:    
    - linux

branches:
  only:
  - gh-pages
  - /.*/
    
compiler:
    - gcc
    
addons:
  apt:
    packages:
      - valgrind
      - cppcheck
      - make
      - cmake
      - lcov

env:
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Release

install:
    - source ci/travis/install-$TRAVIS_OS_NAME

script:
    - gcc -g -Wall -Wextra -std=c99 -c patterns.c
    - ls
    - ar rc libpatterns.a patterns.o
    - ranlib libpatterns.a
    - gcc -g -Wall -Wextra -std=c99 -fPIC -c fork_patterns.c
    - gcc -g -Wall -Wextra -std=c99 -shared -o libfork_patterns.so fork_patterns.o
    - gcc -g -Wall -Wextra -std=c99 -L. -lpatterns -shared -o libfork_patterns.so fork_patterns.o
    - gcc -g -Wall -Wextra -std=c99 test.c -L. -lfork_patterns -lpatterns -o test
    - gcc -g -Wall -Wextra -std=c99 fork_test.c -L. -lfork_patterns -lpatterns -o fork_test
    - LD_LIBRARY_PATH="." time ./test
    - LD_LIBRARY_PATH="." time ./fork_test
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
    - cmake --build .
