dist:     trusty    
sudo:     required  

language: c         
                    
os:    
    - linux

branches:
  only:
  - gh-pages
  - /.*/
    
compiler:
    - gcc
    
addons:
  apt:
    packages:
      - valgrind
      - cppcheck
      - make
      - cmake
      - lcov

env:
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Release

install:
    - source ci/travis/install-$TRAVIS_OS_NAME

script:
    - gcc -g -Wall -Wextra -c patterns.c
    - ar rc libpatterns.a patterns.o
    - ranlib libpatterns.a
    - gcc -g -Wall -Wextra -fPIC -c fork_patterns.c
    - gcc -g -Wall -Wextra -shared -o libfork_patterns.so fork_patterns.o
    - gcc -g -Wall -Wextra -L. -lpatterns -shared -o libfork_patterns.so fork_patterns.o
    - LD_LIBRARY_PATH="." time ./test
    - LD_LIBRARY_PATH="." time ./fork_test
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then valgrind --error-exitcode=1 --leak-check=full --show-leak-kinds=all ./test ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then valgrind --error-exitcode=1 --leak-check=full --show-leak-kinds=all ./fork_test ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cppcheck --error-exitcode=1 --enable=warning,performance,information,style *.c *.h ; fi
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
    - cmake --build .
